#!/bin/sh
# Gỡ icon app khỏi SpringBoard trước khi xóa package
if [ -x "/var/jb/usr/bin/uicache" ]; then
    /var/jb/usr/bin/uicache -u /var/jb/Applications/ExportImageNFC.app
elif [ -x "/usr/bin/uicache" ]; then
    /usr/bin/uicache -u /var/jb/Applications/ExportImageNFC.app
fi
exit 0
